# Darvoza demo — one-click prep (run from the repo root)
# Does: loads secrets from the gitignored repo-root .env → pins policy/audit paths → pre-clears
# audit → opens audit-tail + rogue-caller windows → starts gateway → prints the demo checklist.
# Then YOU: reconnect the client and follow the list (RUNBOOK.md has the full walkthrough).
# NO secret values are printed, stored, or generated by this script — they live only in .env.
#
# .env must contain (same file the gateway itself auto-loads via DotEnvLoader):
#   ADO_ORG, AZURE_DEVOPS_EXT_PAT, DARVOZA_KEY_ANALYST, DARVOZA_KEY_ENGINEER
# The DARVOZA_KEY_* values must match what's pasted in the Claude Desktop connector config.

$ErrorActionPreference = "Stop"
if (-not (Test-Path ".\src\Darvoza.Gateway")) { Write-Host "Run me from the darvoza repo root!" -ForegroundColor Red; exit 1 }
$root = (Get-Location).Path

# --- 1. Secrets: parse repo-root .env into THIS process's env (children inherit it) ---
# The gateway loads .env itself (DotEnvLoader), but RogueCaller and the helper windows read plain
# env vars — so mirror DotEnvLoader's semantics here: trim, skip blanks/#, split on first '=',
# strip one pair of matching quotes, and NEVER overwrite a var that is already set.
$envFile = Join-Path $root ".env"
if (-not (Test-Path $envFile)) { Write-Host "No .env at repo root — see header for required keys (RUNBOOK step 1 has the manual path)." -ForegroundColor Red; exit 1 }
$loaded = @()
foreach ($raw in Get-Content $envFile) {
    $line = $raw.Trim()
    if ($line.Length -eq 0 -or $line.StartsWith('#')) { continue }
    $eq = $line.IndexOf('=')
    if ($eq -le 0) { continue }
    $key = $line.Substring(0, $eq).Trim()
    $val = $line.Substring($eq + 1).Trim()
    if ($val.Length -ge 2 -and ($val[0] -eq '"' -or $val[0] -eq "'") -and $val[-1] -eq $val[0]) { $val = $val.Substring(1, $val.Length - 2) }
    if ($null -eq [Environment]::GetEnvironmentVariable($key)) {
        [Environment]::SetEnvironmentVariable($key, $val)
        $loaded += $key   # names only — values are never echoed
    }
}
Write-Host "Loaded from .env (names only): $($loaded -join ', ')"

$missing = @("ADO_ORG", "AZURE_DEVOPS_EXT_PAT", "DARVOZA_KEY_ANALYST", "DARVOZA_KEY_ENGINEER") |
    Where-Object { [string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($_)) }
if ($missing) { Write-Host "Missing in .env / environment: $($missing -join ', ')" -ForegroundColor Red; exit 1 }

# Pin policy + audit to the repo root unless .env already pinned them — NOT optional: `dotnet run
# --project` runs the gateway with CWD = src\Darvoza.Gateway (RunWorkingDirectory), so without these
# the gateway fails startup looking for src\Darvoza.Gateway\policy.yaml and the tail below would
# watch a file that is never written.
if (-not $env:DARVOZA_POLICY_PATH) { $env:DARVOZA_POLICY_PATH = Join-Path $root "policy.yaml" }
if (-not $env:DARVOZA_AUDIT_PATH)  { $env:DARVOZA_AUDIT_PATH  = Join-Path $root "audit\darvoza-audit.jsonl" }

# --- 2. Policy + pre-clear audit trail (both possible stale locations from earlier runs) ---
if (-not (Test-Path ".\policy.yaml")) { Copy-Item .\policy.example.yaml .\policy.yaml; Write-Host "policy.yaml created from example" }
foreach ($stale in @($env:DARVOZA_AUDIT_PATH, ".\src\Darvoza.Gateway\audit\darvoza-audit.jsonl")) {
    if (Test-Path $stale) { Remove-Item $stale -Force; Write-Host "Stale audit trail cleared: $stale" }
}

# --- 3. Two helper windows (children inherit the env vars set above) ---
# 3a. Audit tail — on-camera terminal #2.
Start-Process powershell -ArgumentList "-NoExit","-Command",
  "`$Host.UI.RawUI.WindowTitle='darvoza audit tail'; while (-not (Test-Path `$env:DARVOZA_AUDIT_PATH)) { Start-Sleep 1 }; Get-Content `$env:DARVOZA_AUDIT_PATH -Wait -Tail 10" `
  -WorkingDirectory $root
# 3b. Rogue-caller shell for the call-level deny — this window has the keys; a fresh terminal would NOT.
Start-Process powershell -ArgumentList "-NoExit","-Command",
  "`$Host.UI.RawUI.WindowTitle='rogue caller (call-level deny)'; Write-Host 'Call-level deny — run:' -ForegroundColor Yellow; Write-Host '  dotnet run --project demo\tools\RogueCaller' -ForegroundColor Yellow; Write-Host '(analyst key is the default; exit code 1 = the intended DENY)' -ForegroundColor DarkGray" `
  -WorkingDirectory $root

# --- 4. Gateway (foreground in THIS window — leave it running) ---
Write-Host @"

====================  DEMO CHECKLIST (RUNBOOK.md)  =====================
 0. AFTER the gateway below says it's listening: reconnect BOTH connectors
    in your MCP client (gateway must be up before the client connects).
    Check analyst tool list has NO wit_create_work_item.
 1. policy.example.yaml: analyst vs engineer allowlists
 2. Connector list + analyst tool list (no create tool)
 3. Analyst client: ask to create -> client refuses
 4. In the 'rogue caller' window: RogueCaller with ANALYST key
    -> DENY + audit line  (see RUNBOOK step 5 flags)
 5. Engineer client: same create -> item on ADO board + allow line
 6. Both audit lines side by side: same tool, opposite decision
 Secrets rule: PAT, keys, and the .env FILE stay off screen — do not open
 .env in any editor tab if you are screen-sharing or recording.
========================================================================

Starting gateway on :5000 ... (Ctrl+C to stop after recording)
"@ -ForegroundColor Cyan
dotnet run --project src/Darvoza.Gateway
